---
- name: install Cockpit in Fedora
  dnf:
    name: cockpit
    state: present
  when: ansible_distribution == "Fedora"
- name: install Cockpit in CentOS
  yum:
    name: cockpit
    state: present
  when: ansible_distribution == "CentOS"
- name: configure Cockpit service
  service:
    name: cockpit.socket
    state: started
    enabled: yes
