---
- name: install cockpit
  package:
    name: cockpit
    state: present
  become: yes
- name: start and enable cockpit service
  service:
    name: cockpit.socket
    state: started
    enabled: yes
  become: yes
